# MATRIX OPERATIONS

In [2]:
import numpy as np
A = np.array([[2, 4,2], [5, -6,-4], [-2,5,-7]])
B = np.array([[9, -3,5], [3, 6,6], [5,-3,-4]])
C = A + B      # element wise addition
print(C)

[[ 11   1   7]
 [  8   0   2]
 [  3   2 -11]]


In [3]:
import numpy as np
A = np.array([[2, 4,2], [5, -6,-4], [-2,5,-7]])
B = np.array([[9, -3,5], [3, 6,6], [5,-3,-4]])
C = A - B      # element wise subtraction
print(C)

[[ -7   7  -3]
 [  2 -12 -10]
 [ -7   8  -3]]


In [4]:
import numpy as np
A = np.array([[2, 4,2], [5, -6,-4], [-2,5,-7]])
B = np.array([[9, -3,5], [3, 6,6], [5,-3,-4]])
C = A *B      # element wise multiply
print(C)

[[ 18 -12  10]
 [ 15 -36 -24]
 [-10 -15  28]]
